name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'adopt'
      - name: Make gradlew executable
        run: chmod +x ./ronebot-starter/starter-frontend/gradlew
      - name: Build
        run: cd ronebot-starter/starter-frontend && ./gradlew :starterFrontendApp:wasmJsBrowserDevelopmentExecutableDistribution
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          projectName: "ronebot-starter-frontend"
          apiToken: ${{ secrets.CF_API_TOKEN }}
          directory: ronebot-starter/starter-frontend/starterFrontendApp/build/dist/wasmJs/developmentExecutable/
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
