name: Deploy to Vercel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: delete previous branch
        run: |
          git branch -D deploy || true
          git push origin --delete deploy || true
      - name: create deploy branch
        run: |
          git checkout --orphan deploy
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'adopt'
      - name: Make gradlew executable
        run: chmod +x ./ronebot-starter/starter-frontend/gradlew
      - name: Build
        run: cd ronebot-starter/starter-frontend && ./gradlew :starterFrontendApp:wasmJsBrowserDevelopmentExecutableDistribution
      - name: move artifacts
        run: |
          mkdir deploy-dist
          mv ronebot-starter/starter-frontend/starterFrontendApp/build/dist/wasmJs/developmentExecutable/* deploy-dist/
      - name: configure git
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
      - name: set remote url
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
      - name: push artifacts
        run: |
          git add deploy-dist
          git commit -m "Deploy Web App $(date +'%Y-%m-%d %H:%M:%S')"
          git push -u origin deploy --force
