name: Publish Dokka API docs

on:
  push:
    branches: [ main ]

jobs:
  build:
    permissions:
      id-token: write
      pages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: 'adopt'
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Build documentation
        run: ./gradlew dokkaHtmlMultiModule
      - name: Upload site artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'build/dokka/htmlMultiModule'

  deploy:
    permissions:
      id-token: write
      pages: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4